#make sure pillow and tkinterdnd2 are installed in order to run this
import os
import re
import math
import random
import tkinter as tk
from tkinter import ttk, filedialog, messagebox, colorchooser

try:
    from tkinterdnd2 import TkinterDnD, DND_FILES
    HAS_DND = True
except Exception:
    TkinterDnD = None
    DND_FILES = None
    HAS_DND = False

from PIL import Image, ImageTk, ImageEnhance, ImageFilter, ImageOps, ImageDraw, ImageChops

APP_TITLE = "RetroImageMaker"
PREVIEW_SIZE = (512, 512)
GRID_THUMB_SIZE = (256, 256)
MAX_PREVIEW_PROCESS_SIZE = 1600 

# Built-in palettes
PICO8_PALETTE = [
    (0, 0, 0), (29, 43, 83), (126, 37, 83), (0, 135, 81),
    (171, 82, 54), (95, 87, 79), (194, 195, 199), (255, 241, 232),
    (255, 0, 77), (255, 163, 0), (255, 236, 39), (0, 228, 54),
    (41, 173, 255), (131, 118, 156), (255, 119, 168), (255, 204, 170)
]
GAMEBOY_DMG_PALETTE = [
    (15, 56, 15), (48, 98, 48), (139, 172, 15), (155, 188, 15)
]
C64_PALETTE = [
    (0, 0, 0), (255, 255, 255), (136, 0, 0), (170, 255, 238),
    (204, 68, 204), (0, 170, 0), (0, 0, 170), (238, 238, 119),
    (221, 136, 85), (102, 68, 0), (255, 119, 119), (51, 51, 51),
    (119, 119, 119), (170, 255, 102), (102, 136, 255), (187, 187, 187)
]
ZX_SPECTRUM_8 = [
    (0, 0, 0), (0, 0, 192), (192, 0, 0), (192, 0, 192),
    (0, 192, 0), (0, 192, 192), (192, 192, 0), (192, 192, 192)
]
EGA16_PALETTE = [
    (0, 0, 0), (0, 0, 170), (0, 170, 0), (0, 170, 170),
    (170, 0, 0), (170, 0, 170), (170, 85, 0), (170, 170, 170),
    (85, 85, 85), (85, 85, 255), (85, 255, 85), (85, 255, 255),
    (255, 85, 85), (255, 85, 255), (255, 255, 85), (255, 255, 255)
]
APPLE2_LORES_16 = [
    (0, 0, 0), (147, 11, 124), (31, 53, 211), (187, 54, 255),
    (0, 118, 12), (126, 126, 126), (7, 168, 224), (157, 172, 255),
    (98, 76, 0), (249, 86, 29), (126, 126, 126), (255, 129, 236),
    (67, 200, 0), (220, 205, 22), (93, 247, 132), (255, 255, 255)
]
NES_NESTOPIA_54 = [
    (255,255,255),(173,173,173),(99,99,99),(0,0,0),(189,222,255),(99,173,255),(25,99,214),(0,41,140),
    (214,214,255),(148,148,255),(66,66,255),(16,16,165),(247,197,255),(197,115,255),(115,41,255),(58,0,165),
    (247,197,255),(239,107,255),(156,25,206),(90,0,123),(255,197,230),(255,107,206),(181,33,123),(107,0,66),
    (255,206,197),(255,132,115),(181,49,33),(107,8,0),(247,214,165),(230,156,33),(156,74,0),(82,33,0),
    (230,230,148),(189,189,0),(107,107,0),(49,49,0),(206,239,148),(140,214,0),(58,132,0),(8,74,0),
    (189,247,173),(90,230,49),(16,148,0),(0,82,0),(181,247,206),(66,222,132),(0,140,49),(0,82,8),
    (181,239,239),(74,206,222),(0,123,140),(0,66,74),(181,181,181),(82,82,82)
]

# Custom palette stuff
CUSTOM_PALETTES = {
    "My Palette": list(PICO8_PALETTE),
}
DEFAULT_CUSTOM_NAME = "My Palette"

CUTE_MODES = [
    "None",
    "Pastel",
    "Cute",
    "CRT",
    "Sticker Outline",
    "Handheld Screen",
    "Postcard Frame",
    "Creepy",
    "Yellowed Photo",
    "Drawing",
]

CUTE_MODE_SHORTCUTS = [
    ("Pastel", "Pastel"),
    ("Cute", "Cute"),
    ("CRT", "CRT"),
    ("Sticker", "Sticker Outline"),
    ("Handheld", "Handheld Screen"),
    ("Postcard", "Postcard Frame"),
    ("Creepy", "Creepy"),
    ("Yellowed", "Yellowed Photo"),
    ("Drawing", "Drawing"),
]


def clamp8(v):
    return max(0, min(255, int(v)))


def parse_hex_color(s: str):
    s = s.strip().lstrip('#')
    if len(s) == 3:
        s = ''.join(ch * 2 for ch in s)
    if len(s) != 6:
        raise ValueError("Hex must be either #RRGGBB or #RGB")
    r, g, b = int(s[0:2], 16), int(s[2:4], 16), int(s[4:6], 16)
    return (r, g, b)


def to_hex(rgb):
    r, g, b = rgb
    return f"#{r:02X}{g:02X}{b:02X}"


def load_gpl(path: str):
    """Load GIMP/Aseprite .gpl palette files."""
    colors = []
    with open(path, 'r', encoding='utf-8', errors='ignore') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#') or line.lower().startswith('gimp palette') or line.lower().startswith('name:') or line.lower().startswith('columns:'):
                continue
            parts = line.split()
            if len(parts) >= 3:
                try:
                    r, g, b = [clamp8(int(parts[i])) for i in range(3)]
                    colors.append((r, g, b))
                except Exception:
                    continue
    if not colors:
        raise ValueError("No colors found in .gpl provided")
    return colors[:256]


def save_gpl(path: str, palette, name="Custom"):
    lines = []
    lines.append("GIMP Palette\n")
    lines.append(f"Name: {name}\n")
    lines.append("Columns: 16\n")
    lines.append("# Generated by RetroImageMaker\n")
    for i, (r, g, b) in enumerate(palette):
        lines.append(f"{r:3d} {g:3d} {b:3d}\tcolor{i + 1}\n")
    with open(path, 'w', encoding='utf-8') as f:
        f.writelines(lines)


def load_jasc_pal(path: str):
    colors = []
    with open(path, 'r', encoding='utf-8', errors='ignore') as f:
        lines = [ln.strip() for ln in f if ln.strip()]
    if len(lines) < 3 or lines[0] != "JASC-PAL":
        raise ValueError("Not a JASC-PAL file")
    try:
        n = int(lines[2])
    except Exception:
        raise ValueError("Invalid color count in .pal")
    for ln in lines[3:3 + n]:
        parts = ln.split()
        if len(parts) >= 3:
            r, g, b = [clamp8(int(parts[i])) for i in range(3)]
            colors.append((r, g, b))
    if not colors:
        raise ValueError("No colors found in .pal")
    return colors[:256]


def save_jasc_pal(path: str, palette):
    lines = ["JASC-PAL\n", "0100\n", f"{len(palette)}\n"]
    for (r, g, b) in palette:
        lines.append(f"{r} {g} {b}\n")
    with open(path, 'w', encoding='utf-8') as f:
        f.writelines(lines)


def fit_image_for_preview(img: Image.Image, max_size=PREVIEW_SIZE) -> Image.Image:
    img = img.copy()
    img.thumbnail(max_size, resample=Image.LANCZOS)
    return img


def downscale_for_preview_processing(img: Image.Image, max_side=MAX_PREVIEW_PROCESS_SIZE) -> Image.Image:
    img = img.copy()
    w, h = img.size
    longest = max(w, h)
    if longest <= max_side:
        return img
    scale = max_side / float(longest)
    new_size = (max(1, int(w * scale)), max(1, int(h * scale)))
    return img.resize(new_size, resample=Image.LANCZOS)


def build_palette_image(palette_colors):
    pal_img = Image.new('P', (1, 1))
    flat = []
    for (r, g, b) in palette_colors:
        flat += [int(r), int(g), int(b)]
    if len(palette_colors) < 256:
        flat += [0, 0, 0] * (256 - len(palette_colors))
    pal_img.putpalette(flat)
    return pal_img


def quantize_to_palette(img: Image.Image, palette_colors, dither: bool) -> Image.Image:
    pal_img = build_palette_image(palette_colors)
    dither_flag = Image.FLOYDSTEINBERG if dither else Image.NONE
    quant = img.convert('RGB').quantize(palette=pal_img, dither=dither_flag)
    return quant.convert('RGB')


def pixelate(img: Image.Image, pixel_size: int) -> Image.Image:
    w, h = img.size
    pixel_size = max(1, int(pixel_size))
    small_w = max(1, w // pixel_size)
    small_h = max(1, h // pixel_size)
    small = img.resize((small_w, small_h), resample=Image.BILINEAR)
    result = small.resize((w, h), resample=Image.NEAREST)
    return result


def enhance_arcade(img: Image.Image) -> Image.Image:
    img = ImageEnhance.Contrast(img).enhance(1.2)
    img = ImageEnhance.Color(img).enhance(1.1)
    return img


def _snap_channel(channel: Image.Image, bits: int) -> Image.Image:
    levels = (1 << bits) - 1

    def _map(v):
        return int(round((v / 255.0) * levels)) * (255 // levels)

    return channel.point(_map)


def snap_rgb_bits(img: Image.Image, bits: int) -> Image.Image:
    r, g, b = img.convert('RGB').split()
    r = _snap_channel(r, bits)
    g = _snap_channel(g, bits)
    b = _snap_channel(b, bits)
    return Image.merge('RGB', (r, g, b))


def snap_rgb333(img: Image.Image) -> Image.Image:
    return snap_rgb_bits(img, 3)


def snap_rgb555(img: Image.Image) -> Image.Image:
    return snap_rgb_bits(img, 5)


def snap_rgb666(img: Image.Image) -> Image.Image:
    return snap_rgb_bits(img, 6)


def apply_nes_emphasis(palette, emphasize_r=False, emphasize_g=False, emphasize_b=False):
    r_factor = 1.0 if emphasize_r else 0.85
    g_factor = 1.0 if emphasize_g else 0.85
    b_factor = 1.0 if emphasize_b else 0.85
    out = []
    for (r, g, b) in palette:
        rr = max(0, min(255, int(r * r_factor)))
        gg = max(0, min(255, int(g * g_factor)))
        bb = max(0, min(255, int(b * b_factor)))
        out.append((rr, gg, bb))
    return out


# ---- Genesis non-linear VDP curve ----
GENESIS_LEVELS = [0, 52, 87, 116, 144, 172, 206, 255]


def apply_genesis_vdp_curve(img: Image.Image) -> Image.Image:
    lut = []
    for v in range(256):
        nearest = min(GENESIS_LEVELS, key=lambda x: abs(x - v))
        lut.append(nearest)
    r, g, b = img.convert('RGB').split()
    r = r.point(lut)
    g = g.point(lut)
    b = b.point(lut)
    return Image.merge('RGB', (r, g, b))


STYLES = [
    "PICO-8 (16 colors)",
    "Game Boy (4 colors)",
    "Commodore 64 (16 colors)",
    "ZX Spectrum (8 colors)",
    "EGA 16",
    "Apple II (Lo-Res 16)",
    "Game Boy Color (RGB555, 32 colors)",
    "Game Boy Advance (RGB555, 64 colors)",
    "Nintendo DS (RGB666, 64 colors)",
    "PlayStation (PS1, RGB555, 32 colors)",
    "Sega Genesis / Mega Drive (RGB333, 64 colors)",
    "NES (Nestopia 54-color)",
    "Nintendo 64 (RGBA5551-like, 64 colors)",
    "Adaptive 32-color (Arcade-like)",
    "Custom Palette (User)",
]


def apply_style(img: Image.Image, style: str, pixel_size: int, dither: bool,
                nes_r=False, nes_g=False, nes_b=False,
                genesis_vdp=False, ps1_movie=False,
                n64_mode="RGBA5551", custom_palette=None) -> Image.Image:
    work = pixelate(img, pixel_size)
    if style == "PICO-8 (16 colors)":
        work = quantize_to_palette(work, PICO8_PALETTE, dither)
    elif style == "Game Boy (4 colors)":
        work = ImageEnhance.Brightness(work).enhance(1.05)
        work = quantize_to_palette(work, GAMEBOY_DMG_PALETTE, dither)
    elif style == "Commodore 64 (16 colors)":
        work = quantize_to_palette(work, C64_PALETTE, dither)
    elif style == "ZX Spectrum (8 colors)":
        work = quantize_to_palette(work, ZX_SPECTRUM_8, dither)
    elif style == "EGA 16":
        work = quantize_to_palette(work, EGA16_PALETTE, dither)
    elif style == "Apple II (Lo-Res 16)":
        work = quantize_to_palette(work, APPLE2_LORES_16, dither)
    elif style == "Game Boy Color (RGB555, 32 colors)":
        work = snap_rgb555(work)
        dither_flag = Image.FLOYDSTEINBERG if dither else Image.NONE
        work = work.convert('RGB').quantize(colors=32, method=0, dither=dither_flag).convert('RGB')
    elif style == "Game Boy Advance (RGB555, 64 colors)":
        work = snap_rgb555(work)
        dither_flag = Image.FLOYDSTEINBERG if dither else Image.NONE
        work = work.convert('RGB').quantize(colors=64, method=0, dither=dither_flag).convert('RGB')
    elif style == "Nintendo DS (RGB666, 64 colors)":
        work = snap_rgb666(work)
        dither_flag = Image.FLOYDSTEINBERG if dither else Image.NONE
        work = work.convert('RGB').quantize(colors=64, method=0, dither=dither_flag).convert('RGB')
    elif style == "PlayStation (PS1, RGB555, 32 colors)":
        work = snap_rgb555(work)
        blur_radius = 1.2 if ps1_movie else 0.5
        work = work.filter(ImageFilter.GaussianBlur(radius=blur_radius))
        if not ps1_movie:
            dither_flag = Image.FLOYDSTEINBERG if dither else Image.NONE
            work = work.convert('RGB').quantize(colors=32, method=0, dither=dither_flag).convert('RGB')
    elif style == "Sega Genesis / Mega Drive (RGB333, 64 colors)":
        work = snap_rgb333(work)
        if genesis_vdp:
            work = apply_genesis_vdp_curve(work)
        dither_flag = Image.FLOYDSTEINBERG if dither else Image.NONE
        work = work.convert('RGB').quantize(colors=64, method=0, dither=dither_flag).convert('RGB')
    elif style == "NES (Nestopia 54-color)":
        pal = apply_nes_emphasis(NES_NESTOPIA_54, nes_r, nes_g, nes_b)
        work = quantize_to_palette(work, pal, dither)
    elif style == "Nintendo 64 (RGBA5551-like, 64 colors)":
        work = work.filter(ImageFilter.GaussianBlur(radius=0.6))
        work = snap_rgb555(work)
        dither_flag = Image.FLOYDSTEINBERG if dither else Image.NONE
        if n64_mode == "CI8":
            work = work.convert('RGB').quantize(colors=256, method=0, dither=dither_flag).convert('RGB')
        elif n64_mode == "CI4":
            work = work.convert('RGB').quantize(colors=16, method=0, dither=dither_flag).convert('RGB')
        else:
            work = work.convert('RGB').quantize(colors=64, method=0, dither=dither_flag).convert('RGB')
    elif style == "Adaptive 32-color (Arcade-like)":
        work = enhance_arcade(work)
        dither_flag = Image.FLOYDSTEINBERG if dither else Image.NONE
        work = work.convert('RGB').quantize(colors=32, method=0, dither=dither_flag).convert('RGB')
    elif style == "Custom Palette (User)":
        pal = custom_palette if custom_palette else CUSTOM_PALETTES.get(DEFAULT_CUSTOM_NAME, [])
        if not pal:
            raise ValueError("Custom palette is empty. Edit or import a palette.")
        work = quantize_to_palette(work, pal, dither)
    return work


#custom mode helpers

def _soft_light_blend(base: Image.Image, overlay: Image.Image, alpha=0.35) -> Image.Image:
    return Image.blend(base.convert('RGB'), overlay.convert('RGB'), max(0.0, min(1.0, alpha)))


def _add_vignette(img: Image.Image, strength=0.35):
    img = img.convert('RGB')
    w, h = img.size
    mask = Image.new('L', (w, h), 255)
    draw = ImageDraw.Draw(mask)
    cx, cy = w / 2.0, h / 2.0
    max_dist = math.sqrt(cx * cx + cy * cy)
    px = mask.load()
    for y in range(h):
        for x in range(w):
            d = math.sqrt((x - cx) ** 2 + (y - cy) ** 2) / max_dist
            v = int(255 * (1.0 - strength * (d ** 1.8)))
            px[x, y] = max(0, min(255, v))
    return ImageChops.multiply(img, Image.merge('RGB', (mask, mask, mask)))


def cute_pastel(img: Image.Image) -> Image.Image:
    img = img.convert('RGB')
    img = ImageEnhance.Color(img).enhance(0.78)
    img = ImageEnhance.Contrast(img).enhance(0.92)
    img = ImageEnhance.Brightness(img).enhance(1.08)
    overlay = Image.new('RGB', img.size, (255, 225, 240))
    overlay2 = Image.new('RGB', img.size, (215, 235, 255))
    blended = _soft_light_blend(img, overlay, 0.22)
    blended = _soft_light_blend(blended, overlay2, 0.12)
    return blended


def cute_kawaii(img: Image.Image) -> Image.Image:
    img = cute_pastel(img)
    img = ImageEnhance.Brightness(img).enhance(1.06)
    img = ImageEnhance.Sharpness(img).enhance(1.15)
    base = img.convert('RGBA')
    overlay = Image.new('RGBA', base.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(overlay)
    w, h = base.size
    seed = (w * 73856093) ^ (h * 19349663)
    rnd = random.Random(seed)
    sparkle_count = max(8, min(36, (w * h) // 45000))
    for _ in range(sparkle_count):
        x = rnd.randint(10, max(11, w - 11))
        y = rnd.randint(10, max(11, h - 11))
        s = rnd.randint(3, 8)
        color = rnd.choice([
            (255, 255, 255, 150),
            (255, 220, 240, 140),
            (220, 240, 255, 140),
            (255, 245, 180, 130),
        ])
        draw.line((x - s, y, x + s, y), fill=color, width=1)
        draw.line((x, y - s, x, y + s), fill=color, width=1)
    return Image.alpha_composite(base, overlay).convert('RGB')


def cute_crt(img: Image.Image) -> Image.Image:
    base = img.convert('RGB')
    base = ImageEnhance.Color(base).enhance(1.1)
    base = ImageEnhance.Contrast(base).enhance(1.08)
    r, g, b = base.split()
    r = ImageChops.offset(r, 1, 0)
    b = ImageChops.offset(b, -1, 0)
    chroma = Image.merge('RGB', (r, g, b)).filter(ImageFilter.GaussianBlur(radius=0.5))
    w, h = chroma.size
    scan = Image.new('L', (w, h), 255)
    px = scan.load()
    for y in range(h):
        v = 230 if y % 2 == 0 else 255
        for x in range(w):
            px[x, y] = v
    chroma = ImageChops.multiply(chroma, Image.merge('RGB', (scan, scan, scan)))
    chroma = _add_vignette(chroma, 0.22)
    return chroma


def cute_sticker_outline(img: Image.Image) -> Image.Image:
    base = img.convert('RGBA')
    w, h = base.size
    pad = max(18, min(80, int(min(w, h) * 0.07)))
    shadow_pad = pad + 8
    canvas = Image.new('RGBA', (w + shadow_pad * 2, h + shadow_pad * 2), (0, 0, 0, 0))
    shadow = Image.new('RGBA', canvas.size, (0, 0, 0, 0))
    sd = ImageDraw.Draw(shadow)
    shadow_box = (shadow_pad + 6, shadow_pad + 8, shadow_pad + 6 + w + pad * 2, shadow_pad + 8 + h + pad * 2)
    sd.rounded_rectangle(shadow_box, radius=max(16, pad), fill=(0, 0, 0, 90))
    shadow = shadow.filter(ImageFilter.GaussianBlur(radius=10))
    canvas = Image.alpha_composite(canvas, shadow)
    draw = ImageDraw.Draw(canvas)
    box = (shadow_pad, shadow_pad, shadow_pad + w + pad * 2, shadow_pad + h + pad * 2)
    draw.rounded_rectangle(box, radius=max(16, pad), fill=(255, 255, 255, 255))
    inner_box = (shadow_pad + pad, shadow_pad + pad, shadow_pad + pad + w, shadow_pad + pad + h)
    rounded = Image.new('RGBA', (w, h), (0, 0, 0, 0))
    rounded.paste(base, (0, 0))
    canvas.paste(rounded, (inner_box[0], inner_box[1]), rounded)
    return canvas


def cute_handheld_screen(img: Image.Image) -> Image.Image:
    screen = img.convert('RGB')
    screen = ImageOps.colorize(ImageOps.grayscale(screen), black=(15, 45, 15), white=(186, 220, 120))
    screen = ImageEnhance.Contrast(screen).enhance(1.18)
    w, h = screen.size
    bezel = max(18, int(min(w, h) * 0.08))
    footer = int(bezel * 1.35)
    canvas = Image.new('RGB', (w + bezel * 2, h + bezel * 2 + footer), (198, 188, 165))
    draw = ImageDraw.Draw(canvas)
    draw.rounded_rectangle((0, 0, canvas.width - 1, canvas.height - 1), radius=max(18, bezel), fill=(208, 200, 182), outline=(110, 104, 95), width=2)
    screen_box = (bezel, bezel, bezel + w, bezel + h)
    draw.rounded_rectangle((screen_box[0] - 6, screen_box[1] - 6, screen_box[2] + 6, screen_box[3] + 6), radius=12, fill=(70, 74, 60))
    canvas.paste(screen, (screen_box[0], screen_box[1]))
    sc = canvas.crop(screen_box)
    sc = cute_crt(sc)
    canvas.paste(sc, (screen_box[0], screen_box[1]))
    cy = h + bezel * 2 + footer // 2
    draw.ellipse((bezel + 20, cy - 12, bezel + 44, cy + 12), fill=(150, 145, 135), outline=(88, 83, 77))
    draw.ellipse((bezel + 56, cy - 12, bezel + 80, cy + 12), fill=(150, 145, 135), outline=(88, 83, 77))
    bx = canvas.width - bezel - 86
    draw.ellipse((bx, cy - 22, bx + 30, cy + 8), fill=(165, 98, 108), outline=(100, 64, 68))
    draw.ellipse((bx + 36, cy - 8, bx + 66, cy + 22), fill=(165, 98, 108), outline=(100, 64, 68))
    return canvas


def cute_postcard_frame(img: Image.Image) -> Image.Image:
    photo = img.convert('RGB')
    photo = ImageEnhance.Color(photo).enhance(1.05)
    w, h = photo.size
    border = max(28, int(min(w, h) * 0.08))
    caption_h = max(36, int(border * 1.6))
    canvas = Image.new('RGB', (w + border * 2, h + border * 2 + caption_h), (250, 246, 238))
    draw = ImageDraw.Draw(canvas)
    canvas.paste(photo, (border, border))
    draw.rectangle((border - 1, border - 1, border + w, border + h), outline=(218, 208, 192), width=1)
    draw.rectangle((0, 0, canvas.width - 1, canvas.height - 1), outline=(225, 215, 200), width=2)
    sx0 = canvas.width - border - 46
    sy0 = border + 10
    for i in range(6):
        draw.arc((sx0 - 6, sy0 - 6 + i * 6, sx0 + 42, sy0 + 20 + i * 6), start=80, end=280, fill=(170, 120, 120), width=1)
    draw.rectangle((sx0, sy0, sx0 + 36, sy0 + 46), outline=(180, 110, 110), width=2)
    y = h + border + caption_h // 2
    draw.line((border + 20, y, canvas.width - border - 20, y), fill=(208, 196, 180), width=1)
    return canvas


def cute_creepy(img: Image.Image) -> Image.Image:
    base = img.convert('RGB')
    base = ImageEnhance.Color(base).enhance(0.72)
    base = ImageEnhance.Contrast(base).enhance(1.25)
    base = ImageEnhance.Sharpness(base).enhance(1.2)
    overlay = Image.new('RGB', base.size, (40, 65, 95))
    cold = _soft_light_blend(base, overlay, 0.22)
    cold = _add_vignette(cold, 0.42)
    noise = Image.effect_noise(cold.size, 8).convert('L')
    noise = ImageEnhance.Contrast(noise).enhance(1.6)
    noise_rgb = Image.merge('RGB', (noise, noise, noise))
    cold = Image.blend(cold, noise_rgb, 0.06)
    r, g, b = cold.split()
    r = ImageChops.offset(r, -2, 0)
    g = ImageChops.offset(g, 1, 0)
    return Image.merge('RGB', (r, g, b))


def cute_yellowed_photo(img: Image.Image) -> Image.Image:
    gray = ImageOps.grayscale(img.convert('RGB'))
    sepia = ImageOps.colorize(gray, black=(80, 60, 35), white=(250, 235, 190))
    sepia = ImageEnhance.Contrast(sepia).enhance(0.92)
    sepia = ImageEnhance.Brightness(sepia).enhance(1.04)
    sepia = _add_vignette(sepia, 0.18)
    paper = Image.effect_noise(sepia.size, 5).convert('L')
    paper = ImageEnhance.Contrast(paper).enhance(0.5)
    paper_rgb = Image.merge('RGB', (paper, paper, paper))
    return Image.blend(sepia, paper_rgb, 0.045)


def cute_drawing(img: Image.Image) -> Image.Image:
    rgb = img.convert('RGB')
    gray = ImageOps.grayscale(rgb)
    inv = ImageOps.invert(gray)
    blur = inv.filter(ImageFilter.GaussianBlur(radius=12))
    g = gray.load()
    b = blur.load()
    out = Image.new('L', gray.size)
    o = out.load()
    for y in range(gray.size[1]):
        for x in range(gray.size[0]):
            gv = g[x, y]
            bv = b[x, y]
            if bv >= 255:
                o[x, y] = 255
            else:
                o[x, y] = min(255, int((gv * 255) / max(1, 255 - bv)))
    edges = gray.filter(ImageFilter.FIND_EDGES)
    edges = ImageOps.invert(edges)
    edges = ImageEnhance.Contrast(edges).enhance(1.8)
    merged = Image.blend(out, edges, 0.18)
    return Image.merge('RGB', (merged, merged, merged))


def apply_cute_mode(img: Image.Image, cute_mode: str) -> Image.Image:
    cute_mode = (cute_mode or "None").strip()
    if cute_mode == "None":
        return img
    if cute_mode == "Pastel":
        return cute_pastel(img)
    if cute_mode == "Cute":
        return cute_kawaii(img)
    if cute_mode == "CRT":
        return cute_crt(img)
    if cute_mode == "Sticker Outline":
        return cute_sticker_outline(img)
    if cute_mode == "Handheld Screen":
        return cute_handheld_screen(img)
    if cute_mode == "Postcard Frame":
        return cute_postcard_frame(img)
    if cute_mode == "Creepy":
        return cute_creepy(img)
    if cute_mode == "Yellowed Photo":
        return cute_yellowed_photo(img)
    if cute_mode == "Drawing":
        return cute_drawing(img)
    return img


# ---------------- drag & drop helpers ----------------

def parse_dnd_files(data: str):
    """Parse TkDND file data into file paths."""
    if not data:
        return []
    data = data.strip()
    out = []
    token_re = re.compile(r'\{[^}]*\}|\S+')
    for token in token_re.findall(data):
        token = token.strip()
        if token.startswith('{') and token.endswith('}'):
            token = token[1:-1]
        token = token.strip()
        if token:
            out.append(token)
    return out


# Palette editor stuff
class PaletteEditor(tk.Toplevel):
    SWATCH_SIZE = 22
    COLS = 16

    def __init__(self, parent, palettes_dict: dict, selected_name: str, on_commit):
        super().__init__(parent)
        self.title("Palette Editor")
        self.resizable(False, False)
        self.transient(parent)
        self.grab_set()
        self.palettes = palettes_dict
        self.on_commit = on_commit
        self.name_var = tk.StringVar(value=selected_name if selected_name in self.palettes else DEFAULT_CUSTOM_NAME)
        self.hex_var = tk.StringVar(value="#FFFFFF")
        self.selected_index = None

        top = ttk.Frame(self, padding=10)
        top.pack(fill=tk.X)
        ttk.Label(top, text="Palette:").grid(row=0, column=0, sticky="w", padx=(0, 4))
        self.name_cb = ttk.Combobox(top, state="readonly", values=list(self.palettes.keys()), textvariable=self.name_var, width=28)
        self.name_cb.grid(row=0, column=1, sticky="w")
        self.name_cb.bind("<<ComboboxSelected>>", lambda e: self._reload_grid())
        ttk.Button(top, text="New…", command=self._new_palette).grid(row=0, column=2, padx=4)
        ttk.Button(top, text="Rename…", command=self._rename_palette).grid(row=0, column=3, padx=4)
        ttk.Button(top, text="Delete", command=self._delete_palette).grid(row=0, column=4, padx=4)

        grid_frame = ttk.LabelFrame(self, text="Colors", padding=10)
        grid_frame.pack(fill=tk.BOTH, expand=True, padx=10, pady=(0, 10))
        self.grid_frame = grid_frame

        ctrl = ttk.Frame(self, padding=(10, 0, 10, 10))
        ctrl.pack(fill=tk.X)
        ttk.Label(ctrl, text="Hex:").grid(row=0, column=0, sticky="e")
        hex_entry = ttk.Entry(ctrl, textvariable=self.hex_var, width=10)
        hex_entry.grid(row=0, column=1, sticky="w", padx=(4, 8))
        ttk.Button(ctrl, text="Add / Replace", command=self._add_or_replace_from_hex).grid(row=0, column=2, padx=4)
        ttk.Button(ctrl, text="Eyedropper…", command=self._eyedropper).grid(row=0, column=3, padx=4)
        ttk.Button(ctrl, text="Remove", command=self._remove_selected).grid(row=0, column=4, padx=4)
        ttk.Button(ctrl, text="Up", command=lambda: self._move_selected(-1)).grid(row=0, column=5, padx=2)
        ttk.Button(ctrl, text="Down", command=lambda: self._move_selected(1)).grid(row=0, column=6, padx=2)
        ttk.Button(ctrl, text="Clear", command=self._clear_palette).grid(row=0, column=7, padx=8)

        bottom = ttk.Frame(self, padding=10)
        bottom.pack(fill=tk.X)
        ttk.Button(bottom, text="Import…", command=self._import_palette).pack(side=tk.LEFT)
        ttk.Button(bottom, text="Export…", command=self._export_palette).pack(side=tk.LEFT, padx=6)
        ttk.Label(bottom, text="(supports .gpl and JASC .pal)", foreground="#555").pack(side=tk.LEFT, padx=6)
        ttk.Button(bottom, text="Use This Palette", command=self._commit).pack(side=tk.RIGHT)
        ttk.Button(bottom, text="Close", command=self.destroy).pack(side=tk.RIGHT, padx=6)

        self._build_grid()
        self._reload_grid()

    def _build_grid(self):
        for w in list(self.grid_frame.children.values()):
            w.destroy()
        self.swatch_btns = []
        for i in range(256):
            r = i // self.COLS
            c = i % self.COLS
            btn = tk.Label(self.grid_frame, width=2, height=1, relief="solid", bd=1, cursor="hand2")
            btn.grid(row=r, column=c, padx=2, pady=2)
            btn.bind("<Button-1>", lambda e, idx=i: self._on_swatch_click(idx))
            self.swatch_btns.append(btn)

    def _reload_grid(self):
        name = self.name_var.get()
        if name not in self.palettes:
            self.palettes[name] = []
        pal = self.palettes[name]
        for i, btn in enumerate(self.swatch_btns):
            if i < len(pal):
                rgb = pal[i]
                btn.configure(bg=to_hex(rgb))
            else:
                btn.configure(bg=self.cget("bg"))
        self.selected_index = None
        self.name_cb.configure(values=list(self.palettes.keys()))
        self.name_cb.set(name)

    def _on_swatch_click(self, idx: int):
        name = self.name_var.get()
        pal = self.palettes.get(name, [])
        self.selected_index = idx if idx < len(pal) else None
        if self.selected_index is not None:
            self.hex_var.set(to_hex(pal[self.selected_index]))
        for i, btn in enumerate(self.swatch_btns):
            btn.configure(highlightthickness=2 if i == self.selected_index else 0, highlightbackground="#333")

    def _add_or_replace_from_hex(self):
        try:
            rgb = parse_hex_color(self.hex_var.get())
        except Exception as e:
            messagebox.showerror("Hex error", str(e), parent=self)
            return
        name = self.name_var.get()
        pal = self.palettes.get(name, [])
        if self.selected_index is None:
            if len(pal) >= 256:
                messagebox.showinfo("Palette full", "Maximum 256 colors.", parent=self)
                return
            pal.append(rgb)
        else:
            pal[self.selected_index] = rgb
        self.palettes[name] = pal
        self._reload_grid()

    def _eyedropper(self):
        color = colorchooser.askcolor(parent=self, title="Pick a color")
        if color and color[0] is not None:
            r, g, b = [clamp8(v) for v in color[0]]
            self.hex_var.set(to_hex((r, g, b)))
            self._add_or_replace_from_hex()

    def _remove_selected(self):
        name = self.name_var.get()
        pal = self.palettes.get(name, [])
        if self.selected_index is not None and self.selected_index < len(pal):
            pal.pop(self.selected_index)
            self.selected_index = None
            self._reload_grid()

    def _move_selected(self, delta):
        name = self.name_var.get()
        pal = self.palettes.get(name, [])
        i = self.selected_index
        if i is None or i < 0 or i >= len(pal):
            return
        j = i + delta
        if 0 <= j < len(pal):
            pal[i], pal[j] = pal[j], pal[i]
            self.selected_index = j
            self._reload_grid()
            self._on_swatch_click(j)

    def _clear_palette(self):
        name = self.name_var.get()
        if messagebox.askyesno("Clear palette", f"Remove all colors from '{name}'?", parent=self):
            self.palettes[name] = []
            self.selected_index = None
            self._reload_grid()

    def _new_palette(self):
        new_name = self._ask_text("New Palette", "Name:", default="New Palette")
        if not new_name:
            return
        if new_name in self.palettes:
            messagebox.showerror("Exists", "A palette with that name already exists.", parent=self)
            return
        self.palettes[new_name] = []
        self.name_var.set(new_name)
        self._reload_grid()

    def _rename_palette(self):
        curr = self.name_var.get()
        new_name = self._ask_text("Rename Palette", "New name:", default=curr)
        if not new_name or new_name == curr:
            return
        if new_name in self.palettes:
            messagebox.showerror("Exists", "A palette with that name already exists.", parent=self)
            return
        self.palettes[new_name] = self.palettes.pop(curr)
        self.name_var.set(new_name)
        self._reload_grid()

    def _delete_palette(self):
        name = self.name_var.get()
        if messagebox.askyesno("Delete palette", f"Delete '{name}'?", parent=self):
            try:
                del self.palettes[name]
            except KeyError:
                pass
            if not self.palettes:
                self.palettes[DEFAULT_CUSTOM_NAME] = []
                self.name_var.set(DEFAULT_CUSTOM_NAME)
            else:
                self.name_var.set(list(self.palettes.keys())[0])
            self._reload_grid()

    def _import_palette(self):
        path = filedialog.askopenfilename(
            title="Import Palette",
            filetypes=[("Palettes", ".gpl .pal"), ("GIMP/Aseprite .gpl", ".gpl"),
                       ("JASC-PAL .pal", ".pal"), ("All files", "*.*")]
        )
        if not path:
            return
        try:
            ext = os.path.splitext(path)[1].lower()
            if ext == ".gpl":
                pal = load_gpl(path)
            elif ext == ".pal":
                pal = load_jasc_pal(path)
            else:
                raise ValueError("Unsupported extension")
            base = os.path.splitext(os.path.basename(path))[0]
            name = base
            suffix = 1
            while name in self.palettes:
                suffix += 1
                name = f"{base} ({suffix})"
            self.palettes[name] = pal
            self.name_var.set(name)
            self._reload_grid()
        except Exception as e:
            messagebox.showerror("Import failed", str(e), parent=self)

    def _export_palette(self):
        name = self.name_var.get()
        pal = self.palettes.get(name, [])
        if not pal:
            messagebox.showinfo("Empty palette", "Nothing to export.", parent=self)
            return
        path = filedialog.asksaveasfilename(
            title="Export Palette",
            defaultextension=".gpl",
            initialfile=f"{name}.gpl",
            filetypes=[("GIMP/Aseprite .gpl", ".gpl"), ("JASC-PAL .pal", ".pal"), ("All files", "*.*")]
        )
        if not path:
            return
        try:
            ext = os.path.splitext(path)[1].lower()
            if ext == ".gpl":
                save_gpl(path, pal, name=name)
            elif ext == ".pal":
                save_jasc_pal(path, pal)
            else:
                raise ValueError("Choose .gpl or .pal")
            messagebox.showinfo("Exported", f"Saved palette to:\n{path}", parent=self)
        except Exception as e:
            messagebox.showerror("Export failed", str(e), parent=self)

    def _commit(self):
        if callable(self.on_commit):
            self.on_commit(self.name_var.get())
        self.destroy()

    def _ask_text(self, title, prompt, default=""):
        win = tk.Toplevel(self)
        win.title(title)
        win.transient(self)
        win.grab_set()
        ttk.Label(win, text=prompt, padding=10).pack()
        var = tk.StringVar(value=default)
        entry = ttk.Entry(win, textvariable=var, width=30)
        entry.pack(padx=10)
        entry.focus_set()
        btns = ttk.Frame(win, padding=10)
        btns.pack()
        out = {"val": None}

        def ok():
            out["val"] = var.get().strip()
            win.destroy()

        def cancel():
            win.destroy()

        ttk.Button(btns, text="OK", command=ok).pack(side=tk.LEFT, padx=5)
        ttk.Button(btns, text="Cancel", command=cancel).pack(side=tk.LEFT, padx=5)
        self.wait_window(win)
        return out["val"]


class PixelArtApp:
    def __init__(self, root: tk.Tk):
        self.root = root
        root.title(APP_TITLE)

        # State
        self.original_image = None
        self.original_path = None
        self.processed_image = None
        self.preview_photo = None
        self.compare_photos = []
        self.preview_job = None

        # Custom palette state
        self.custom_palettes = {k: list(v) for k, v in CUSTOM_PALETTES.items()}
        self.current_palette_name = DEFAULT_CUSTOM_NAME

        # Cute mode state
        self.cute_mode_var = tk.StringVar(value="None")

        # Notebook
        self.nb = ttk.Notebook(root)
        self.nb.pack(fill=tk.BOTH, expand=True)
        self.single_tab = ttk.Frame(self.nb)
        self.nb.add(self.single_tab, text="Single Style")
        self.compare_tab = ttk.Frame(self.nb)
        self.nb.add(self.compare_tab, text="Compare All")

        controls = ttk.Frame(self.single_tab, padding=10)
        controls.pack(side=tk.TOP, fill=tk.X)
        self.load_btn = ttk.Button(controls, text="Load Image…", command=self.load_image)
        self.load_btn.grid(row=0, column=0, padx=(0, 8), pady=4, sticky="w")

        ttk.Label(controls, text="Style:").grid(row=0, column=1, padx=(0, 4), pady=4, sticky="e")
        self.style_var = tk.StringVar(value=STYLES[0])
        self.style_cb = ttk.Combobox(controls, textvariable=self.style_var, values=STYLES, state="readonly", width=36)
        self.style_cb.grid(row=0, column=2, padx=(0, 8), pady=4, sticky="w")
        self.style_cb.bind("<<ComboboxSelected>>", lambda e: (self._update_palette_visibility(), self.update_processing()))

        # Palette section
        self.palette_frame = ttk.Frame(controls)
        self.palette_frame.grid(row=0, column=3, columnspan=3, sticky="w", padx=(0, 8))
        ttk.Label(self.palette_frame, text="Palette:").grid(row=0, column=0, padx=(0, 4), pady=4, sticky="e")
        self.palette_var = tk.StringVar(value=self.current_palette_name)
        self.palette_cb = ttk.Combobox(self.palette_frame, textvariable=self.palette_var,
                                       values=list(self.custom_palettes.keys()), state="readonly", width=24)
        self.palette_cb.grid(row=0, column=1, padx=(0, 4), pady=4, sticky="w")
        self.palette_cb.bind("<<ComboboxSelected>>", self._on_palette_changed)
        self.edit_pal_btn = ttk.Button(self.palette_frame, text="Edit Palettes…", command=self.open_palette_editor)
        self.edit_pal_btn.grid(row=0, column=2, padx=(0, 8), pady=4, sticky="w")

        ttk.Label(controls, text="Pixel size:").grid(row=0, column=6, padx=(0, 4), pady=4, sticky="e")
        self.pixel_var = tk.IntVar(value=12)
        self.pixel_slider = ttk.Scale(controls, from_=4, to=48, orient=tk.HORIZONTAL, command=self.on_slider)
        self.pixel_slider.grid(row=0, column=7, padx=(0, 8), pady=4, sticky="we")
        controls.columnconfigure(7, weight=1)

        self.pixel_label = ttk.Label(controls, text=f"{self.pixel_var.get()} px")
        self.pixel_label.grid(row=0, column=8, padx=(0, 8), pady=4, sticky="w")
        self.pixel_slider.set(self.pixel_var.get())

        self.dither_var = tk.BooleanVar(value=False)
        self.dither_chk = ttk.Checkbutton(controls, text="Dithering", variable=self.dither_var, command=self.update_processing)
        self.dither_chk.grid(row=0, column=9, padx=(0, 8), pady=4, sticky="w")
        self.save_btn = ttk.Button(controls, text="Save Pixel Art…", command=self.save_image)
        self.save_btn.grid(row=0, column=10, padx=(0, 8), pady=4, sticky="e")

        # Cute modes section
        cute = ttk.LabelFrame(self.single_tab, text="Preset Modes (one click)", padding=10)
        cute.pack(side=tk.TOP, fill=tk.X, padx=10, pady=(0, 10))

        top_cute = ttk.Frame(cute)
        top_cute.pack(fill=tk.X, pady=(0, 6))
        ttk.Label(top_cute, text="Current:").pack(side=tk.LEFT)
        self.cute_mode_cb = ttk.Combobox(top_cute, textvariable=self.cute_mode_var, values=CUTE_MODES, state="readonly", width=18)
        self.cute_mode_cb.pack(side=tk.LEFT, padx=(6, 12))
        self.cute_mode_cb.bind("<<ComboboxSelected>>", lambda e: self.update_processing())
        ttk.Button(top_cute, text="Reset", command=lambda: self.set_cute_mode("None")).pack(side=tk.LEFT, padx=(0, 12))

        cute_row_wrap = ttk.Frame(cute)
        cute_row_wrap.pack(fill=tk.X)
        self.cute_canvas = tk.Canvas(cute_row_wrap, height=42, highlightthickness=0, borderwidth=0)
        self.cute_canvas.pack(side=tk.TOP, fill=tk.X, expand=True)
        cute_x_scroll = ttk.Scrollbar(cute_row_wrap, orient=tk.HORIZONTAL, command=self.cute_canvas.xview)
        cute_x_scroll.pack(side=tk.TOP, fill=tk.X)
        self.cute_canvas.configure(xscrollcommand=cute_x_scroll.set)
        self.cute_inner = ttk.Frame(self.cute_canvas)
        self.cute_canvas_window = self.cute_canvas.create_window((0, 0), window=self.cute_inner, anchor='nw')
        self.cute_inner.bind("<Configure>", self._on_cute_inner_configure)
        self.cute_canvas.bind("<Configure>", self._on_cute_canvas_configure)

        for i, (label, mode) in enumerate(CUTE_MODE_SHORTCUTS):
            ttk.Button(self.cute_inner, text=label, command=lambda m=mode: self.set_cute_mode(m)).grid(row=0, column=i, padx=4, pady=4, sticky="w")

        adv = ttk.LabelFrame(self.single_tab, text="Advanced options", padding=10)
        adv.pack(side=tk.TOP, fill=tk.X, padx=10, pady=(0, 10))
        ttk.Label(adv, text="NES Emphasis:").grid(row=0, column=0, sticky="e")
        self.nes_r = tk.BooleanVar(value=False)
        self.nes_g = tk.BooleanVar(value=False)
        self.nes_b = tk.BooleanVar(value=False)
        chk_r = ttk.Checkbutton(adv, text="Red", variable=self.nes_r, command=self.update_processing)
        chk_g = ttk.Checkbutton(adv, text="Green", variable=self.nes_g, command=self.update_processing)
        chk_b = ttk.Checkbutton(adv, text="Blue", variable=self.nes_b, command=self.update_processing)
        chk_r.grid(row=0, column=1, sticky="w")
        chk_g.grid(row=0, column=2, sticky="w")
        chk_b.grid(row=0, column=3, sticky="w")
        self.nes_controls_children = [chk_r, chk_g, chk_b]

        self.genesis_vdp = tk.BooleanVar(value=False)
        ttk.Checkbutton(adv, text="Genesis non-linear VDP levels", variable=self.genesis_vdp, command=self.update_processing).grid(row=0, column=4, padx=10, sticky="w")
        self.ps1_movie = tk.BooleanVar(value=False)
        ttk.Checkbutton(adv, text="PS1 24-bit Movie mode", variable=self.ps1_movie, command=self.update_processing).grid(row=0, column=5, padx=10, sticky="w")
        ttk.Label(adv, text="N64 Texture Mode:").grid(row=0, column=6, sticky="e")
        self.n64_mode = tk.StringVar(value="RGBA5551")
        ttk.Combobox(adv, textvariable=self.n64_mode, values=["RGBA5551", "CI8", "CI4"], state="readonly", width=8).grid(row=0, column=7, padx=4, sticky="w")
        self.n64_mode.trace_add('write', lambda *args: self.update_processing())

        preview_frame = ttk.Frame(self.single_tab, padding=10)
        preview_frame.pack(side=tk.TOP, fill=tk.BOTH, expand=True)
        self.preview_outer = ttk.Frame(preview_frame)
        self.preview_outer.pack(fill=tk.BOTH, expand=True)
        self.preview_label = ttk.Label(self.preview_outer, text=self._empty_state_text(), anchor="center", justify="center")
        self.preview_label.pack(fill=tk.BOTH, expand=True)
        self.drop_hint = ttk.Label(self.preview_outer, text=self._drop_hint_text(), anchor="center", foreground="#666")
        self.drop_hint.pack(side=tk.BOTTOM, pady=(0, 10))

        compare_controls = ttk.Frame(self.compare_tab, padding=10)
        compare_controls.pack(side=tk.TOP, fill=tk.X)
        ttk.Button(compare_controls, text="Refresh Grid", command=self.refresh_compare).pack(side=tk.LEFT, padx=(0, 8))
        ttk.Button(compare_controls, text="Save All…", command=self.save_all).pack(side=tk.LEFT)
        self.compare_mode_label = ttk.Label(compare_controls, textvariable=self.cute_mode_var, foreground="#666")
        ttk.Label(compare_controls, text="Cute mode:").pack(side=tk.LEFT, padx=(14, 4))
        self.compare_mode_label.pack(side=tk.LEFT)

        self.grid_canvas = tk.Canvas(self.compare_tab, highlightthickness=0)
        self.grid_canvas.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
        self.grid_scroll = ttk.Scrollbar(self.compare_tab, orient=tk.VERTICAL, command=self.grid_canvas.yview)
        self.grid_scroll.pack(side=tk.RIGHT, fill=tk.Y)
        self.grid_canvas.configure(yscrollcommand=self.grid_scroll.set)
        self.grid_inner = ttk.Frame(self.grid_canvas)
        self.grid_window = self.grid_canvas.create_window((0, 0), window=self.grid_inner, anchor='nw')
        self.grid_inner.bind("<Configure>", lambda e: self.grid_canvas.configure(scrollregion=self.grid_canvas.bbox(self.grid_window)))
        self.grid_canvas.bind('<Configure>', self._on_canvas_resize)

        self._update_palette_visibility()
        self._init_drag_and_drop()

    def _on_cute_inner_configure(self, event=None):
        self.cute_canvas.configure(scrollregion=self.cute_canvas.bbox("all"))

    def _on_cute_canvas_configure(self, event):
        self.cute_canvas.itemconfigure(self.cute_canvas_window, height=event.height)

    def _empty_state_text(self):
        if HAS_DND:
            return "Drop an image here or click 'Load Image…'"
        return "Click 'Load Image…' to open an image"

    def _drop_hint_text(self):
        return "You can drag a .png / .jpg / .bmp / .gif file onto the preview area." if HAS_DND else "Tip: install tkinterdnd2 for drag-and-drop."

    def _init_drag_and_drop(self):
        if not HAS_DND:
            return
        targets = [self.root, self.preview_label, self.preview_outer, self.grid_canvas, self.nb]
        for widget in targets:
            try:
                widget.drop_target_register(DND_FILES)
                widget.dnd_bind('<<Drop>>', self._on_drop)
            except Exception:
                pass

    def _on_drop(self, event):
        files = parse_dnd_files(getattr(event, 'data', ''))
        if not files:
            return
        path = files[0]
        self.load_image(path)

    def _on_canvas_resize(self, event):
        self.grid_canvas.itemconfig(self.grid_window, width=event.width)

    def _update_palette_visibility(self):
        is_custom = (self.style_var.get() == "Custom Palette (User)")
        if is_custom:
            if not self.palette_frame.winfo_ismapped():
                self.palette_frame.grid()
        else:
            self.palette_frame.grid_remove()

        nes_enabled = (self.style_var.get() == "NES (Nestopia 54-color)")
        for w in getattr(self, "nes_controls_children", []):
            w.configure(state=("normal" if nes_enabled else "disabled"))

    def set_cute_mode(self, cute_mode):
        self.cute_mode_var.set(cute_mode)
        self.update_processing()

    def _on_palette_changed(self, *_):
        self.current_palette_name = self.palette_var.get()
        self.update_processing()

    def on_slider(self, value):
        val = int(float(value))
        self.pixel_var.set(val)
        if hasattr(self, 'pixel_label'):
            self.pixel_label.configure(text=f"{val} px")
        if self.preview_job is not None:
            try:
                self.root.after_cancel(self.preview_job)
            except Exception:
                pass
        self.preview_job = self.root.after(90, self.update_processing)

    def load_image(self, path=None):
        if not path:
            filetypes = [
                ("Image files", ".png .jpg .jpeg .bmp .gif"),
                ("PNG", ".png"), ("JPEG", ".jpg .jpeg"), ("Bitmap", ".bmp"), ("GIF", ".gif"), ("All files", "*.*"),
            ]
            path = filedialog.askopenfilename(title="Select an image", filetypes=filetypes)
        if not path:
            return
        try:
            img = Image.open(path).convert('RGB')
            self.original_image = img
            self.original_path = path
            self.update_processing()
            self.refresh_compare()
        except Exception as e:
            messagebox.showerror("Error", f"Could not open image:\n{e}")

    def _get_selected_custom_palette(self):
        name = self.current_palette_name
        return self.custom_palettes.get(name, [])

    def _render_current_image(self, source_img: Image.Image):
        style = self.style_var.get()
        pixel_size = int(self.pixel_var.get())
        dither = bool(self.dither_var.get())
        custom_pal = self._get_selected_custom_palette() if style == "Custom Palette (User)" else None
        out = apply_style(
            source_img, style, pixel_size, dither,
            nes_r=self.nes_r.get(), nes_g=self.nes_g.get(), nes_b=self.nes_b.get(),
            genesis_vdp=self.genesis_vdp.get(), ps1_movie=self.ps1_movie.get(),
            n64_mode=self.n64_mode.get(), custom_palette=custom_pal
        )
        out = apply_cute_mode(out, self.cute_mode_var.get())
        return out

    def update_processing(self):
        if self.original_image is None:
            return
        try:
            preview_source = downscale_for_preview_processing(self.original_image)
            preview_result = self._render_current_image(preview_source)
            self.processed_image = self._render_current_image(self.original_image)
            preview_img = fit_image_for_preview(preview_result, PREVIEW_SIZE)
            self.preview_photo = ImageTk.PhotoImage(preview_img)
            self.preview_label.configure(image=self.preview_photo, text="")
            self.drop_hint.configure(text=self._drop_hint_text())
        except Exception as e:
            messagebox.showerror("Error", f"Processing failed:\n{e}")

    def refresh_compare(self):
        for w in list(self.grid_inner.children.values()):
            w.destroy()
        self.compare_photos.clear()
        if self.original_image is None:
            ttk.Label(self.grid_inner, text="Load an image to compare styles.").grid(row=0, column=0, padx=10, pady=10, sticky='w')
            return

        pixel_size = int(self.pixel_var.get())
        dither = bool(self.dither_var.get())
        cols = 2
        r = c = 0
        source = downscale_for_preview_processing(self.original_image, max_side=1200)

        for style in STYLES:
            try:
                if style == "Custom Palette (User)":
                    pal = self._get_selected_custom_palette()
                    if not pal:
                        frame = ttk.Frame(self.grid_inner, padding=6)
                        ttk.Label(frame, text="Custom Palette (User)").pack()
                        ttk.Label(frame, text="(No colors in selected palette)").pack()
                        frame.grid(row=r, column=c, sticky='nwe')
                        c += 1
                        if c >= cols:
                            c = 0
                            r += 1
                        continue
                custom_pal = self._get_selected_custom_palette() if style == "Custom Palette (User)" else None
                out = apply_style(
                    source, style, pixel_size, dither,
                    nes_r=self.nes_r.get(), nes_g=self.nes_g.get(), nes_b=self.nes_b.get(),
                    genesis_vdp=self.genesis_vdp.get(), ps1_movie=self.ps1_movie.get(),
                    n64_mode=self.n64_mode.get(),
                    custom_palette=custom_pal
                )
                out = apply_cute_mode(out, self.cute_mode_var.get())
                thumb = fit_image_for_preview(out, GRID_THUMB_SIZE)
                photo = ImageTk.PhotoImage(thumb)
                self.compare_photos.append(photo)
                frame = ttk.Frame(self.grid_inner, padding=6)
                ttk.Label(frame, image=photo).pack()
                ttk.Label(frame, text=style).pack()
                frame.grid(row=r, column=c, sticky='nwe')
                c += 1
                if c >= cols:
                    c = 0
                    r += 1
            except Exception as e:
                frame = ttk.Frame(self.grid_inner, padding=6)
                ttk.Label(frame, text=f"{style}: error {e}").pack()
                frame.grid(row=r, column=c, sticky='nwe')
                c += 1
                if c >= cols:
                    c = 0
                    r += 1

    def save_image(self):
        if self.original_image is None:
            messagebox.showinfo("Save", "Please load an image first.")
            return
        path = filedialog.asksaveasfilename(
            title="Save pixel art",
            defaultextension=".png",
            filetypes=[("PNG", ".png"), ("JPEG", ".jpg .jpeg"), ("BMP", ".bmp"), ("All files", "*.*")]
        )
        if not path:
            return
        try:
            img = self._render_current_image(self.original_image)
            ext = os.path.splitext(path)[1].lower()
            if ext in (".jpg", ".jpeg") and img.mode != 'RGB':
                img = img.convert('RGB')
            img.save(path)
            messagebox.showinfo("Saved", f"Pixel art saved to:\n{path}")
        except Exception as e:
            messagebox.showerror("Error", f"Could not save image:\n{e}")

    def save_all(self):
        if self.original_image is None:
            messagebox.showinfo("Save All", "Please load an image first.")
            return
        folder = filedialog.askdirectory(title="Select folder to save all styles")
        if not folder:
            return
        pixel_size = int(self.pixel_var.get())
        dither = bool(self.dither_var.get())
        count = 0
        errors = []
        for style in STYLES:
            try:
                custom_pal = self._get_selected_custom_palette() if style == "Custom Palette (User)" else None
                out = apply_style(
                    self.original_image, style, pixel_size, dither,
                    nes_r=self.nes_r.get(), nes_g=self.nes_g.get(), nes_b=self.nes_b.get(),
                    genesis_vdp=self.genesis_vdp.get(), ps1_movie=self.ps1_movie.get(),
                    n64_mode=self.n64_mode.get(),
                    custom_palette=custom_pal
                )
                out = apply_cute_mode(out, self.cute_mode_var.get())
                safe = style.replace('/', '-').replace('(', '').replace(')', '').replace(',', '').replace(' ', '_')
                cute = self.cute_mode_var.get().replace(' ', '_')
                path = os.path.join(folder, f"pixel_{safe}__{cute}.png")
                out.save(path)
                count += 1
            except Exception as e:
                errors.append(f"{style}: {e}")
        msg = f"Saved {count} images to\n{folder}"
        if errors:
            msg += "\n\nErrors:\n" + "\n".join(errors)
        messagebox.showinfo("Save All", msg)

    def open_palette_editor(self):
        def on_commit(name):
            self.current_palette_name = name
            self.palette_var.set(name)
            self.palette_cb.configure(values=list(self.custom_palettes.keys()))
            self.update_processing()
            self.refresh_compare()

        PaletteEditor(self.root, self.custom_palettes, self.current_palette_name, on_commit)


# -------------------- app entry --------------------
def main():
    if HAS_DND:
        root = TkinterDnD.Tk()
    else:
        root = tk.Tk()
    try:
        style = ttk.Style()
        if "clam" in style.theme_names():
            style.theme_use("clam")
    except Exception:
        pass
    app = PixelArtApp(root)
    root.geometry("1120x860")
    root.minsize(860, 640)
    root.mainloop()


if __name__ == "__main__":
    main()
